---

apiVersion: v1
data:
  POSTGRES_PASSWORD: "1234"
  POSTGRES_USER: database
kind: ConfigMap
metadata:
  name: db-config

---

apiVersion: v1
data:
  DB: postgres://database:1234@db-svc/database
kind: ConfigMap
metadata:
  name: api-config

---

apiVersion: v1
data:
  API_HOST: http://api-svc:3000
  PORT: "8080"
kind: ConfigMap
metadata:
  name: web-config
