---

apiVersion: v1
data:
  POSTGRES_PASSWORD: MTIzNA==
  POSTGRES_USER: ZGF0YWJhc2U=
kind: Secret
metadata:
  name: db-config

---

apiVersion: v1
data:
  DB: cG9zdGdyZXM6Ly9kYXRhYmFzZToxMjM0QGRiLXN2Yy9kYXRhYmFzZQ==
kind: Secret
metadata:
  name: api-config

---

apiVersion: v1
data:
  API_HOST: http://api-svc:3000
  PORT: "8080"
kind: ConfigMap
metadata:
  name: web-config
