on:
  workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow
env:
  CLUSTER_NAME: k8s-test
  CLUSTER_RESOURCE_GROUP: k8s
  NAMESPACE: app
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -
    
    
    # Deploy app to AKS
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          workflow/10-config.yaml
          workflow/11-deploy.yaml
          workflow/12-svc.yaml
        namespace: ${{ env.NAMESPACE }}
